### PR TITLE
balena-jetson-wnb: rename connectivity packagegroup

### PR DESCRIPTION
**Pull request by markcorbinuk**
Rename the resin-connectivity packagegroup.

Change-type: patch
Changelog-entry: balena-jetson-wnb: rename connectivity packagegroup
Signed-off-by: Mark Corbin <mark@balena.io>

### CODE REVIEW

**Comment by markcorbinuk** [comment]
@resin-jenkins add to whitelist

**Comment by markcorbinuk** [comment]
@resin-jenkins ok to build

**Comment by markcorbinuk** [comment]
@resin-jenkins retest this please

**Comment by markcorbinuk** [comment]
@resin-jenkins retest this please

**Comment by markcorbinuk** [comment]
@resin-jenkins ok to build

**Comment by markcorbinuk** [comment]
@resin-jenkins retest this please

**Comment by markcorbinuk** [comment]
@resin-jenkins ok to build

**Comment by markcorbinuk** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
Will be included in a new BSP update PR

**Pull request closed without merging**
